### ISSUE TITLE
Ship a single PSM1 from a tested build and release mechanism

### ISSUE THREAD

**Issue by kilasuit** [vexx32/PSWordCloud#1]
This should be done for neatness & to follow best practices

**Comment by vexx32** [comment]
Should, yes. Mostly I prefer to keep things tidy 🤷‍♂️ 

If someone wants to put that together and PR it, I'll happily link it up to my Azure and get it rolling. But for now this is mainly just a fun lil project. 😄

**Comment by vexx32** [comment]
@thomasrayner I have a DevOps org for PSKoans so I could just add this to that one... so yeah absolutely that'd be awesome ❤️

**Comment by thomasrayner** [comment]
@vexx32 Shoot me an invite and I'll getcha sum goodness. thomasrayner`@`live.ca.

**Comment by vexx32** [comment]
Closing for now as we're shipping a compiled DLL with no PSM1 requirement for the time being. 🙂
