### ISSUE TITLE
Feature Req: Choose orientation of focus word

### ISSUE THREAD

**Issue by thomasrayner** [vexx32/PSWordCloud#19]
It would be pretty cool if you could choose the orientation of the focus word. Maybe even more than just making it horizontal or vertical, but diagonal or something custom. That'd be a ton of fun 😁

**Comment by vexx32** [comment]
Permitting multiple orientations and selections for focus word is a good idea. I'm tempted to limit it to 8 degrees of freedom, so you get rotations at 45, 90, 135, etc.

You'd _probably_ want to allow all words to do that and have a -RotationStyle parameter or something? 🤔 

Not sure on the implementation.

**Comment by thomasrayner** [comment]
I could go either way on it. It might be cool to just have the focus word at a non-standard rotation, and then have all the others go horizontal/vertical. I like the idea of limiting the degrees of freedom.

**Comment by vexx32** [comment]
`-Chaos` switch to just have it pick completely random angles 😂

**Comment by romero126** [comment]
The brain cannot switch orientation that fast.. it stings the eyes.

**Comment by vexx32** [comment]
![test image](https://svgshare.com/i/Bpa.svg)

This is what it sort of looks like when I do something like this. This is a -45 angle on the focus word.
