### ISSUE TITLE
-InputObject not taking my... Object Input

### ISSUE THREAD

**Issue by Windos** [vexx32/PSWordCloud#24]
This is just a result of trying to re-run some older code (from before the SVG update) and running into an issue off the bat. I'd previously used -InputObject, but this isn't working and piping data in is working perfectly.

![image](https://user-images.githubusercontent.com/6955786/54969659-efbfb680-4fe3-11e9-90c8-9ddd49e5a34e.png)

Much like my issue about importing on Windows, I'm not sure if this is intentional or not as I notice all the examples show piping data in.

This is Windows PowerShell on Windows 10 1809. Version 2.1.0 of PSWordCloud.

**Comment by vexx32** [comment]
Can you pull `$error[0].Exception.GetBaseException() | FL * -f` for the first case for me? Seems like that'd get us the most useful data right out the gate.

I think the most obvious solution here is going to be simply figuring out how to call into whatever `Out-String` hooks into from the c# side, as I can't really directly access the cmdlet from inside another cmdlet very easily... Not sure.

**Comment by Windos** [comment]
Sure thing:

```powershell
PS C:\Users\Windos> New-WordCloud -InputObject $TwitterStatuses.text -Path "D:\TwitterStatuses.png"
New-WordCloud : One or more errors occurred.
At line:1 char:1
+ New-WordCloud -InputObject $TwitterStatuses.text -Path "D:\TwitterSta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-WordCloud], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,PSWordCloud.NewWordCloudCommand
 

PS C:\Users\Windos> $error[0].Exception.GetBaseException() | FL * -f


Message        : Object reference not set to an instance of an object.
Data           : {}
InnerException : 
TargetSite     : System.Collections.Generic.IEnumerable`1[System.String] <ProcessInputAsync>b__0()
StackTrace     :    at PSWordCloud.NewWordCloudCommand.<>c__DisplayClass132_0.<ProcessInputAsync>b__0()
                    at System.Threading.Tasks.Task`1.InnerInvoke()
                    at System.Threading.Tasks.Task.Execute()
HelpLink       : 
Source         : PSWordCloudCmdlet
HResult        : -2147467261
```

**Comment by vexx32** [comment]
That's very interesting... Okay, where are you pulling this data from & how? I'll probably need to replicate this and debug it properly to see what's happening.

**Comment by Windos** [comment]
Easiest way to replicate it is the word cloud example in the PSTwitterAPI
intro: https://mkellerman.github.io/Introducing_PSTwitterAPI/

**Comment by vexx32** [comment]
Awesome, I'll run it through.

It's probably me using something that's in .net core, and not .net framework. Can't think of that it might be at the moment though.
