### ISSUE TITLE
Ability to define different type of Word Clouds 

### ISSUE THREAD

**Issue by PrzemyslawKlys** [vexx32/PSWordCloud#3]
I thought I would be having some nice output if I would use 

```
function Get-ComputerDisk {
    param(
        $ComputerName = $Env:COMPUTERNAME
    )
    $Data2 = Get-WmiObject win32_DiskDrive -ComputerName $ComputerName | Select Index, Model, Caption, SerialNumber, Description, MediaType, FirmwareRevision, Partitions, @{Expression = {$_.Size / 1Gb -as [int]}; Label = "Total Size(GB)"}, PNPDeviceID
    return $Data2
}
```

as my data for words. I suspected it may not work :-) 

```
get-clipboard | New-WordCloud -Path wordcloud.png -FontFamily Georgia
```

I kept waiting for minutes and it didn't do anything :-) What I actually wanted is to create some nice output for blogs pictures, especially for featured photo. It takes a lot of effort to create a good blog post and it's even harder to maintain quality photos for Featured Photos so that it doesn't look like a complete trash. 

What I was looking to create was something like this:

![image](https://user-images.githubusercontent.com/15063294/50086003-0e036280-01fc-11e9-9d60-8f17fd29b884.png)

It would be so cool if this project could generate pictures like that. Where it would take some PowerShell code or another type of code and mix it up in colors and produce nice looking featured picture with chosen size. 

I imagine this may be a bit out of the scope of this project thou ;-) 

Something like this - would be cool too

![image](https://user-images.githubusercontent.com/15063294/50086971-0e512d00-01ff-11e9-890f-4db03d74a49d.png)

Or this:

![image](https://user-images.githubusercontent.com/15063294/50087069-2f198280-01ff-11e9-84e1-58834478dcf2.png)

**Comment by vexx32** [comment]
Okay, so this is a lot to think about at once @PrzemyslawKlys. Imma break it out into parts:

# Allowing word rotations

Frankly, can't believe I didn't think of this sooner. Should have had better model images, I guess! I'll look into adding this!

# Arbitrary object input

I think this is what you're asking, right? Pipe in random streams of objects at get usable output for the word cloud?

I think the most pragmatic solution would be to simply take whatever the console would render and attempt to make that work by sending it through `Out-String` to get the string representation. In fact, you can do that already, but it would be nice if this just handled it.

# 3D rotations and filters

3D rotations _should_ be possible using the .NET classes, but I've no idea if they actually are. Will have to research.

I'm pretty sure I've seen filters and can experiment there, though.

I'll mark this as up for grabs in case someone else wants to make any of this happen before I get to it, but I like the ideas a lot!

**Comment by vexx32** [comment]
Different colour backgrounds is exposed as a parameter already. You can also ask it for a transparent background and layer it on whatever.

That said, being able to pass in a background image in is pretty trivial with these methods, so definitely should be a thing! Watermarks... Have to think about how I'd do that. But probably doable!

Predefined image sizes are a thing, you can press tab after specifying the size parameter to see the predefined sizes tab complete for you. If you know of any I'm missing, let me know those and I'll add them!

And yeah, maybe splitting them out into separate issues would be a good idea, just allows us to focus discussion on a single topic and keep track of everything, so we don't miss anything. If you could put an issue in for each, that'd be much appreciated! :smile:
