### ISSUE TITLE
Improve word placements

### ISSUE THREAD

**Issue by vexx32** [vexx32/PSWordCloud#8]
Currently, if a word cannot find a suitable place, the code "gives up" and doesn't care if the word overlaps.
It would be better if the word were simply hidden.

In line with this, there are a couple other improvements to placement we can do: 

- [x] Allow words to extend to the bounds of the image. Currently, they're limited to approximately 3/4 of a rectangular image at the very outside. _Note:_ this may require increasing the maximum word size.
- [x] Skip checking for points that are themselves already outside image bounds.
- [x] Check both possible rotations for words that don't seem to fit at a scan point. This should allow for words to be filled into the gaps a bit better.
- [x] Add optional switch `-IgnoreImageBounds` (name subject to change) to allow users to opt to ignore image bounds checks completely

**Comment by PrzemyslawKlys** [comment]
I was about to create a feature request for this. What I wanted to add is that it would make sense to allow words to be cut in half when it reaches bounds of the image. You don't necessarily need to keep the whole word, part of it would make it look ok as well. Probably via [switch] $AllowCutoff or so ;)

**Comment by vexx32** [comment]
I'll consider adding this back in as a deliberate option after we get the image bounds detection more thoroughly fixed up. 😄

**Comment by vexx32** [comment]
All of these are in 1.4.0. 😄

**Comment by PrzemyslawKlys** [comment]
Woooo, Thank you!
