### ISSUE TITLE
Corrupt image output

### ISSUE THREAD

**Issue by RobinRamaekers1** [vexx32/PSWordCloud#97]
# :bug: Bug Report

## :computer: Environment Data

```none

```

### :x: Actual Behaviour

![unknown](https://user-images.githubusercontent.com/71765356/112999918-a294f300-916f-11eb-9f7d-1367d0bcf152.png)

**Comment by vexx32** [comment]
File output from the module is currently .svg only, I never got around to getting .png output back / got many requests for it to come back.

If you change the extension and open it in a browser or an image editor you should be able to view it without problems. Not sure if Windows 10's default Photos app supports vector formats.

**Comment by vexx32** [comment]
Closing this for now; if you need any additional help just let me know. 🙂
